version: '3.2'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/PHP.Dockerfile
    volumes:
      - .:/app

  server:
    image: nginx:alpine
    container_name: server-nginx
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: app-booking
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
